require "bundler/gem_tasks"
require "rake/testtask"
require_relative 'lib/isomorfeus/speednode/version'

task :bench do
  sh 'ruby -Ilib -r./test/shim test/bench.rb'
end

task :test do
  ENV["EXECJS_RUNTIME"] = 'Speednode'
end

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList['test/shim.rb', 'test/test_isomorfeus_speednode.rb', 'test/test_execjs.rb', 'test/test_permissive_execjs.rb']
end

task :default => :test

task :push_ruby_packages do
  Rake::Task['push_ruby_packages_to_rubygems'].invoke
  Rake::Task['push_ruby_packages_to_github'].invoke
end

task :push_ruby_packages_to_rubygems do
  system("gem push isomorfeus-speednode-#{Isomorfeus::Speednode::VERSION}.gem")
end

task :push_ruby_packages_to_github do
  system("gem push --key github --host https://rubygems.pkg.github.com/isomorfeus isomorfeus-speednode-#{Isomorfeus::Speednode::VERSION}.gem")
end
